# Generated by Django 4.2.7 on 2025-10-23 14:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('nit_ci', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT/CI')),
                ('es_frecuente', models.BooleanField(default=False, verbose_name='Cliente frecuente')),
                ('cantidad_pedidos', models.IntegerField(default=0, verbose_name='Cantidad de pedidos')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del material')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad disponible')),
                ('cantidad_minima', models.IntegerField(default=10, verbose_name='Cantidad mínima')),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('resma', 'Resma'), ('caja', 'Caja')], default='unidad', max_length=50, verbose_name='Unidad de medida')),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proveedor')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Material de Inventario',
                'verbose_name_plural': 'Inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('descripcion', models.TextField(verbose_name='Descripción del pedido')),
                ('especificaciones', models.TextField(blank=True, null=True, verbose_name='Especificaciones técnicas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_produccion', 'En Producción'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega estimada')),
                ('fecha_entregado', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('tipo', models.CharField(choices=[('tarjetas', 'Tarjetas de presentación'), ('volantes', 'Volantes'), ('banners', 'Banners'), ('folletos', 'Folletos'), ('libros', 'Libros'), ('revistas', 'Revistas'), ('otros', 'Otros')], max_length=100, verbose_name='Tipo de producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio unitario')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('terminado', 'Terminado')], default='no_iniciado', max_length=50, verbose_name='Estado de producción')),
                ('tiempo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tiempo estimado (horas)')),
                ('tiempo_real', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Tiempo real (horas)')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones', to=settings.AUTH_USER_MODEL, verbose_name='Empleado asignado')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='core.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('empleado', 'Personal de Producción')], default='empleado', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto de perfil')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.inventario', verbose_name='Material')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='core.produccion', verbose_name='Relacionado a producción')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
