# Generated by Copilot on 2025-10-27
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del proveedor')),
                ('contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ordenado', 'Ordenado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de recepción')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha real de recepción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('stock_aplicado', models.BooleanField(default=False, verbose_name='Stock aplicado')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.inventario', verbose_name='Material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.proveedor', verbose_name='Proveedor')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to='auth.user', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Compra a Proveedor',
                'verbose_name_plural': 'Compras a Proveedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
